/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCharactersCharacterIdNotificationsContacts200Ok = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCharactersCharacterIdNotificationsContacts200Ok model module.
   * @module model/GetCharactersCharacterIdNotificationsContacts200Ok
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdNotificationsContacts200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdNotificationsContacts200Ok
   * @class
   * @param message {String} message string
   * @param notification_id {Number} notification_id integer
   * @param send_date {Date} send_date string
   * @param sender_character_id {Number} sender_character_id integer
   * @param standing_level {Number} A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
   */
  var exports = function(message, notification_id, send_date, sender_character_id, standing_level) {
    this.message = message;
    this.notification_id = notification_id;
    this.send_date = send_date;
    this.sender_character_id = sender_character_id;
    this.standing_level = standing_level;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdNotificationsContacts200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdNotificationsContacts200Ok} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdNotificationsContacts200Ok} The populated <code>GetCharactersCharacterIdNotificationsContacts200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('notification_id'))
        obj.notification_id = ApiClient.convertToType(data['notification_id'], 'Number');
      if (data.hasOwnProperty('send_date'))
        obj.send_date = ApiClient.convertToType(data['send_date'], 'Date');
      if (data.hasOwnProperty('sender_character_id'))
        obj.sender_character_id = ApiClient.convertToType(data['sender_character_id'], 'Number');
      if (data.hasOwnProperty('standing_level'))
        obj.standing_level = ApiClient.convertToType(data['standing_level'], 'Number');
    }
    return obj;
  }

  /**
   * message string
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * notification_id integer
   * @member {Number} notification_id
   */
  exports.prototype.notification_id = undefined;

  /**
   * send_date string
   * @member {Date} send_date
   */
  exports.prototype.send_date = undefined;

  /**
   * sender_character_id integer
   * @member {Number} sender_character_id
   */
  exports.prototype.sender_character_id = undefined;

  /**
   * A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
   * @member {Number} standing_level
   */
  exports.prototype.standing_level = undefined;


  return exports;

}));
