/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCorporationCorporationIdMiningObservers200Ok = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCorporationCorporationIdMiningObservers200Ok model module.
   * @module model/GetCorporationCorporationIdMiningObservers200Ok
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCorporationCorporationIdMiningObservers200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCorporationCorporationIdMiningObservers200Ok
   * @class
   * @param last_updated {Date} last_updated string
   * @param observer_id {Number} The entity that was observing the asteroid field when it was mined. 
   * @param observer_type {module:model/GetCorporationCorporationIdMiningObservers200Ok.ObserverTypeEnum} The category of the observing entity
   */
  var exports = function(last_updated, observer_id, observer_type) {
    this.last_updated = last_updated;
    this.observer_id = observer_id;
    this.observer_type = observer_type;
  };

  /**
   * Constructs a <code>GetCorporationCorporationIdMiningObservers200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationCorporationIdMiningObservers200Ok} obj Optional instance to populate.
   * @return {module:model/GetCorporationCorporationIdMiningObservers200Ok} The populated <code>GetCorporationCorporationIdMiningObservers200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('last_updated'))
        obj.last_updated = ApiClient.convertToType(data['last_updated'], 'Date');
      if (data.hasOwnProperty('observer_id'))
        obj.observer_id = ApiClient.convertToType(data['observer_id'], 'Number');
      if (data.hasOwnProperty('observer_type'))
        obj.observer_type = ApiClient.convertToType(data['observer_type'], 'String');
    }
    return obj;
  }

  /**
   * last_updated string
   * @member {Date} last_updated
   */
  exports.prototype.last_updated = undefined;

  /**
   * The entity that was observing the asteroid field when it was mined. 
   * @member {Number} observer_id
   */
  exports.prototype.observer_id = undefined;

  /**
   * The category of the observing entity
   * @member {module:model/GetCorporationCorporationIdMiningObservers200Ok.ObserverTypeEnum} observer_type
   */
  exports.prototype.observer_type = undefined;



  /**
   * Allowed values for the <code>observer_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ObserverTypeEnum = {
    /**
     * value: "structure"
     * @const
     */
    structure: "structure"
  };

  return exports;

}));
