/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCorporationsCorporationIdOk = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCorporationsCorporationIdOk model module.
   * @module model/GetCorporationsCorporationIdOk
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCorporationsCorporationIdOk</code>.
   * 200 ok object
   * @alias module:model/GetCorporationsCorporationIdOk
   * @class
   * @param ceo_id {Number} ceo_id integer
   * @param creator_id {Number} creator_id integer
   * @param member_count {Number} member_count integer
   * @param name {String} the full name of the corporation
   * @param tax_rate {Number} tax_rate number
   * @param ticker {String} the short name of the corporation
   */
  var exports = function(ceo_id, creator_id, member_count, name, tax_rate, ticker) {
    this.ceo_id = ceo_id;
    this.creator_id = creator_id;
    this.member_count = member_count;
    this.name = name;
    this.tax_rate = tax_rate;
    this.ticker = ticker;
  };

  /**
   * Constructs a <code>GetCorporationsCorporationIdOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationsCorporationIdOk} obj Optional instance to populate.
   * @return {module:model/GetCorporationsCorporationIdOk} The populated <code>GetCorporationsCorporationIdOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('alliance_id'))
        obj.alliance_id = ApiClient.convertToType(data['alliance_id'], 'Number');
      if (data.hasOwnProperty('ceo_id'))
        obj.ceo_id = ApiClient.convertToType(data['ceo_id'], 'Number');
      if (data.hasOwnProperty('creator_id'))
        obj.creator_id = ApiClient.convertToType(data['creator_id'], 'Number');
      if (data.hasOwnProperty('date_founded'))
        obj.date_founded = ApiClient.convertToType(data['date_founded'], 'Date');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('faction_id'))
        obj.faction_id = ApiClient.convertToType(data['faction_id'], 'Number');
      if (data.hasOwnProperty('home_station_id'))
        obj.home_station_id = ApiClient.convertToType(data['home_station_id'], 'Number');
      if (data.hasOwnProperty('member_count'))
        obj.member_count = ApiClient.convertToType(data['member_count'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('shares'))
        obj.shares = ApiClient.convertToType(data['shares'], 'Number');
      if (data.hasOwnProperty('tax_rate'))
        obj.tax_rate = ApiClient.convertToType(data['tax_rate'], 'Number');
      if (data.hasOwnProperty('ticker'))
        obj.ticker = ApiClient.convertToType(data['ticker'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('war_eligible'))
        obj.war_eligible = ApiClient.convertToType(data['war_eligible'], 'Boolean');
    }
    return obj;
  }

  /**
   * ID of the alliance that corporation is a member of, if any
   * @member {Number} alliance_id
   */
  exports.prototype.alliance_id = undefined;

  /**
   * ceo_id integer
   * @member {Number} ceo_id
   */
  exports.prototype.ceo_id = undefined;

  /**
   * creator_id integer
   * @member {Number} creator_id
   */
  exports.prototype.creator_id = undefined;

  /**
   * date_founded string
   * @member {Date} date_founded
   */
  exports.prototype.date_founded = undefined;

  /**
   * description string
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * faction_id integer
   * @member {Number} faction_id
   */
  exports.prototype.faction_id = undefined;

  /**
   * home_station_id integer
   * @member {Number} home_station_id
   */
  exports.prototype.home_station_id = undefined;

  /**
   * member_count integer
   * @member {Number} member_count
   */
  exports.prototype.member_count = undefined;

  /**
   * the full name of the corporation
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * shares integer
   * @member {Number} shares
   */
  exports.prototype.shares = undefined;

  /**
   * tax_rate number
   * @member {Number} tax_rate
   */
  exports.prototype.tax_rate = undefined;

  /**
   * the short name of the corporation
   * @member {String} ticker
   */
  exports.prototype.ticker = undefined;

  /**
   * url string
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * war_eligible boolean
   * @member {Boolean} war_eligible
   */
  exports.prototype.war_eligible = undefined;


  return exports;

}));
