/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCorporationsCorporationIdFwStatsKills', 'model/GetCorporationsCorporationIdFwStatsVictoryPoints'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCorporationsCorporationIdFwStatsKills'), require('./GetCorporationsCorporationIdFwStatsVictoryPoints'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCorporationsCorporationIdFwStatsOk = factory(root.EveApi.ApiClient, root.EveApi.GetCorporationsCorporationIdFwStatsKills, root.EveApi.GetCorporationsCorporationIdFwStatsVictoryPoints);
  }
}(this, function(ApiClient, GetCorporationsCorporationIdFwStatsKills, GetCorporationsCorporationIdFwStatsVictoryPoints) {
  'use strict';

  /**
   * The GetCorporationsCorporationIdFwStatsOk model module.
   * @module model/GetCorporationsCorporationIdFwStatsOk
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCorporationsCorporationIdFwStatsOk</code>.
   * 200 ok object
   * @alias module:model/GetCorporationsCorporationIdFwStatsOk
   * @class
   * @param kills {module:model/GetCorporationsCorporationIdFwStatsKills} 
   * @param victory_points {module:model/GetCorporationsCorporationIdFwStatsVictoryPoints} 
   */
  var exports = function(kills, victory_points) {
    this.kills = kills;
    this.victory_points = victory_points;
  };

  /**
   * Constructs a <code>GetCorporationsCorporationIdFwStatsOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationsCorporationIdFwStatsOk} obj Optional instance to populate.
   * @return {module:model/GetCorporationsCorporationIdFwStatsOk} The populated <code>GetCorporationsCorporationIdFwStatsOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('enlisted_on'))
        obj.enlisted_on = ApiClient.convertToType(data['enlisted_on'], 'Date');
      if (data.hasOwnProperty('faction_id'))
        obj.faction_id = ApiClient.convertToType(data['faction_id'], 'Number');
      if (data.hasOwnProperty('kills'))
        obj.kills = GetCorporationsCorporationIdFwStatsKills.constructFromObject(data['kills']);
      if (data.hasOwnProperty('pilots'))
        obj.pilots = ApiClient.convertToType(data['pilots'], 'Number');
      if (data.hasOwnProperty('victory_points'))
        obj.victory_points = GetCorporationsCorporationIdFwStatsVictoryPoints.constructFromObject(data['victory_points']);
    }
    return obj;
  }

  /**
   * The enlistment date of the given corporation into faction warfare. Will not be included if corporation is not enlisted in faction warfare
   * @member {Date} enlisted_on
   */
  exports.prototype.enlisted_on = undefined;

  /**
   * The faction the given corporation is enlisted to fight for. Will not be included if corporation is not enlisted in faction warfare
   * @member {Number} faction_id
   */
  exports.prototype.faction_id = undefined;

  /**
   * @member {module:model/GetCorporationsCorporationIdFwStatsKills} kills
   */
  exports.prototype.kills = undefined;

  /**
   * How many pilots the enlisted corporation has. Will not be included if corporation is not enlisted in faction warfare
   * @member {Number} pilots
   */
  exports.prototype.pilots = undefined;

  /**
   * @member {module:model/GetCorporationsCorporationIdFwStatsVictoryPoints} victory_points
   */
  exports.prototype.victory_points = undefined;


  return exports;

}));
