/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCharactersCharacterIdNotifications200Ok = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCharactersCharacterIdNotifications200Ok model module.
   * @module model/GetCharactersCharacterIdNotifications200Ok
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdNotifications200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdNotifications200Ok
   * @class
   * @param notification_id {Number} notification_id integer
   * @param sender_id {Number} sender_id integer
   * @param sender_type {module:model/GetCharactersCharacterIdNotifications200Ok.SenderTypeEnum} sender_type string
   * @param timestamp {Date} timestamp string
   * @param type {module:model/GetCharactersCharacterIdNotifications200Ok.TypeEnum} type string
   */
  var exports = function(notification_id, sender_id, sender_type, timestamp, type) {
    this.notification_id = notification_id;
    this.sender_id = sender_id;
    this.sender_type = sender_type;
    this.timestamp = timestamp;
    this.type = type;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdNotifications200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdNotifications200Ok} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdNotifications200Ok} The populated <code>GetCharactersCharacterIdNotifications200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('is_read'))
        obj.is_read = ApiClient.convertToType(data['is_read'], 'Boolean');
      if (data.hasOwnProperty('notification_id'))
        obj.notification_id = ApiClient.convertToType(data['notification_id'], 'Number');
      if (data.hasOwnProperty('sender_id'))
        obj.sender_id = ApiClient.convertToType(data['sender_id'], 'Number');
      if (data.hasOwnProperty('sender_type'))
        obj.sender_type = ApiClient.convertToType(data['sender_type'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Date');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * is_read boolean
   * @member {Boolean} is_read
   */
  exports.prototype.is_read = undefined;

  /**
   * notification_id integer
   * @member {Number} notification_id
   */
  exports.prototype.notification_id = undefined;

  /**
   * sender_id integer
   * @member {Number} sender_id
   */
  exports.prototype.sender_id = undefined;

  /**
   * sender_type string
   * @member {module:model/GetCharactersCharacterIdNotifications200Ok.SenderTypeEnum} sender_type
   */
  exports.prototype.sender_type = undefined;

  /**
   * text string
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * timestamp string
   * @member {Date} timestamp
   */
  exports.prototype.timestamp = undefined;

  /**
   * type string
   * @member {module:model/GetCharactersCharacterIdNotifications200Ok.TypeEnum} type
   */
  exports.prototype.type = undefined;



  /**
   * Allowed values for the <code>sender_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SenderTypeEnum = {
    /**
     * value: "character"
     * @const
     */
    character: "character",

    /**
     * value: "corporation"
     * @const
     */
    corporation: "corporation",

    /**
     * value: "alliance"
     * @const
     */
    alliance: "alliance",

    /**
     * value: "faction"
     * @const
     */
    faction: "faction",

    /**
     * value: "other"
     * @const
     */
    other: "other"
  };


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "AcceptedAlly"
     * @const
     */
    AcceptedAlly: "AcceptedAlly",

    /**
     * value: "AcceptedSurrender"
     * @const
     */
    AcceptedSurrender: "AcceptedSurrender",

    /**
     * value: "AgentRetiredTrigravian"
     * @const
     */
    AgentRetiredTrigravian: "AgentRetiredTrigravian",

    /**
     * value: "AllAnchoringMsg"
     * @const
     */
    AllAnchoringMsg: "AllAnchoringMsg",

    /**
     * value: "AllMaintenanceBillMsg"
     * @const
     */
    AllMaintenanceBillMsg: "AllMaintenanceBillMsg",

    /**
     * value: "AllStrucInvulnerableMsg"
     * @const
     */
    AllStrucInvulnerableMsg: "AllStrucInvulnerableMsg",

    /**
     * value: "AllStructVulnerableMsg"
     * @const
     */
    AllStructVulnerableMsg: "AllStructVulnerableMsg",

    /**
     * value: "AllWarCorpJoinedAllianceMsg"
     * @const
     */
    AllWarCorpJoinedAllianceMsg: "AllWarCorpJoinedAllianceMsg",

    /**
     * value: "AllWarDeclaredMsg"
     * @const
     */
    AllWarDeclaredMsg: "AllWarDeclaredMsg",

    /**
     * value: "AllWarInvalidatedMsg"
     * @const
     */
    AllWarInvalidatedMsg: "AllWarInvalidatedMsg",

    /**
     * value: "AllWarRetractedMsg"
     * @const
     */
    AllWarRetractedMsg: "AllWarRetractedMsg",

    /**
     * value: "AllWarSurrenderMsg"
     * @const
     */
    AllWarSurrenderMsg: "AllWarSurrenderMsg",

    /**
     * value: "AllianceCapitalChanged"
     * @const
     */
    AllianceCapitalChanged: "AllianceCapitalChanged",

    /**
     * value: "AllianceWarDeclaredV2"
     * @const
     */
    AllianceWarDeclaredV2: "AllianceWarDeclaredV2",

    /**
     * value: "AllyContractCancelled"
     * @const
     */
    AllyContractCancelled: "AllyContractCancelled",

    /**
     * value: "AllyJoinedWarAggressorMsg"
     * @const
     */
    AllyJoinedWarAggressorMsg: "AllyJoinedWarAggressorMsg",

    /**
     * value: "AllyJoinedWarAllyMsg"
     * @const
     */
    AllyJoinedWarAllyMsg: "AllyJoinedWarAllyMsg",

    /**
     * value: "AllyJoinedWarDefenderMsg"
     * @const
     */
    AllyJoinedWarDefenderMsg: "AllyJoinedWarDefenderMsg",

    /**
     * value: "BattlePunishFriendlyFire"
     * @const
     */
    BattlePunishFriendlyFire: "BattlePunishFriendlyFire",

    /**
     * value: "BillOutOfMoneyMsg"
     * @const
     */
    BillOutOfMoneyMsg: "BillOutOfMoneyMsg",

    /**
     * value: "BillPaidCorpAllMsg"
     * @const
     */
    BillPaidCorpAllMsg: "BillPaidCorpAllMsg",

    /**
     * value: "BountyClaimMsg"
     * @const
     */
    BountyClaimMsg: "BountyClaimMsg",

    /**
     * value: "BountyESSShared"
     * @const
     */
    BountyESSShared: "BountyESSShared",

    /**
     * value: "BountyESSTaken"
     * @const
     */
    BountyESSTaken: "BountyESSTaken",

    /**
     * value: "BountyPlacedAlliance"
     * @const
     */
    BountyPlacedAlliance: "BountyPlacedAlliance",

    /**
     * value: "BountyPlacedChar"
     * @const
     */
    BountyPlacedChar: "BountyPlacedChar",

    /**
     * value: "BountyPlacedCorp"
     * @const
     */
    BountyPlacedCorp: "BountyPlacedCorp",

    /**
     * value: "BountyYourBountyClaimed"
     * @const
     */
    BountyYourBountyClaimed: "BountyYourBountyClaimed",

    /**
     * value: "BuddyConnectContactAdd"
     * @const
     */
    BuddyConnectContactAdd: "BuddyConnectContactAdd",

    /**
     * value: "CharAppAcceptMsg"
     * @const
     */
    CharAppAcceptMsg: "CharAppAcceptMsg",

    /**
     * value: "CharAppRejectMsg"
     * @const
     */
    CharAppRejectMsg: "CharAppRejectMsg",

    /**
     * value: "CharAppWithdrawMsg"
     * @const
     */
    CharAppWithdrawMsg: "CharAppWithdrawMsg",

    /**
     * value: "CharLeftCorpMsg"
     * @const
     */
    CharLeftCorpMsg: "CharLeftCorpMsg",

    /**
     * value: "CharMedalMsg"
     * @const
     */
    CharMedalMsg: "CharMedalMsg",

    /**
     * value: "CharTerminationMsg"
     * @const
     */
    CharTerminationMsg: "CharTerminationMsg",

    /**
     * value: "CloneActivationMsg"
     * @const
     */
    CloneActivationMsg: "CloneActivationMsg",

    /**
     * value: "CloneActivationMsg2"
     * @const
     */
    CloneActivationMsg2: "CloneActivationMsg2",

    /**
     * value: "CloneMovedMsg"
     * @const
     */
    CloneMovedMsg: "CloneMovedMsg",

    /**
     * value: "CloneRevokedMsg1"
     * @const
     */
    CloneRevokedMsg1: "CloneRevokedMsg1",

    /**
     * value: "CloneRevokedMsg2"
     * @const
     */
    CloneRevokedMsg2: "CloneRevokedMsg2",

    /**
     * value: "CombatOperationFinished"
     * @const
     */
    CombatOperationFinished: "CombatOperationFinished",

    /**
     * value: "ContactAdd"
     * @const
     */
    ContactAdd: "ContactAdd",

    /**
     * value: "ContactEdit"
     * @const
     */
    ContactEdit: "ContactEdit",

    /**
     * value: "ContainerPasswordMsg"
     * @const
     */
    ContainerPasswordMsg: "ContainerPasswordMsg",

    /**
     * value: "ContractRegionChangedToPochven"
     * @const
     */
    ContractRegionChangedToPochven: "ContractRegionChangedToPochven",

    /**
     * value: "CorpAllBillMsg"
     * @const
     */
    CorpAllBillMsg: "CorpAllBillMsg",

    /**
     * value: "CorpAppAcceptMsg"
     * @const
     */
    CorpAppAcceptMsg: "CorpAppAcceptMsg",

    /**
     * value: "CorpAppInvitedMsg"
     * @const
     */
    CorpAppInvitedMsg: "CorpAppInvitedMsg",

    /**
     * value: "CorpAppNewMsg"
     * @const
     */
    CorpAppNewMsg: "CorpAppNewMsg",

    /**
     * value: "CorpAppRejectCustomMsg"
     * @const
     */
    CorpAppRejectCustomMsg: "CorpAppRejectCustomMsg",

    /**
     * value: "CorpAppRejectMsg"
     * @const
     */
    CorpAppRejectMsg: "CorpAppRejectMsg",

    /**
     * value: "CorpBecameWarEligible"
     * @const
     */
    CorpBecameWarEligible: "CorpBecameWarEligible",

    /**
     * value: "CorpDividendMsg"
     * @const
     */
    CorpDividendMsg: "CorpDividendMsg",

    /**
     * value: "CorpFriendlyFireDisableTimerCompleted"
     * @const
     */
    CorpFriendlyFireDisableTimerCompleted: "CorpFriendlyFireDisableTimerCompleted",

    /**
     * value: "CorpFriendlyFireDisableTimerStarted"
     * @const
     */
    CorpFriendlyFireDisableTimerStarted: "CorpFriendlyFireDisableTimerStarted",

    /**
     * value: "CorpFriendlyFireEnableTimerCompleted"
     * @const
     */
    CorpFriendlyFireEnableTimerCompleted: "CorpFriendlyFireEnableTimerCompleted",

    /**
     * value: "CorpFriendlyFireEnableTimerStarted"
     * @const
     */
    CorpFriendlyFireEnableTimerStarted: "CorpFriendlyFireEnableTimerStarted",

    /**
     * value: "CorpKicked"
     * @const
     */
    CorpKicked: "CorpKicked",

    /**
     * value: "CorpLiquidationMsg"
     * @const
     */
    CorpLiquidationMsg: "CorpLiquidationMsg",

    /**
     * value: "CorpNewCEOMsg"
     * @const
     */
    CorpNewCEOMsg: "CorpNewCEOMsg",

    /**
     * value: "CorpNewsMsg"
     * @const
     */
    CorpNewsMsg: "CorpNewsMsg",

    /**
     * value: "CorpNoLongerWarEligible"
     * @const
     */
    CorpNoLongerWarEligible: "CorpNoLongerWarEligible",

    /**
     * value: "CorpOfficeExpirationMsg"
     * @const
     */
    CorpOfficeExpirationMsg: "CorpOfficeExpirationMsg",

    /**
     * value: "CorpStructLostMsg"
     * @const
     */
    CorpStructLostMsg: "CorpStructLostMsg",

    /**
     * value: "CorpTaxChangeMsg"
     * @const
     */
    CorpTaxChangeMsg: "CorpTaxChangeMsg",

    /**
     * value: "CorpVoteCEORevokedMsg"
     * @const
     */
    CorpVoteCEORevokedMsg: "CorpVoteCEORevokedMsg",

    /**
     * value: "CorpVoteMsg"
     * @const
     */
    CorpVoteMsg: "CorpVoteMsg",

    /**
     * value: "CorpWarDeclaredMsg"
     * @const
     */
    CorpWarDeclaredMsg: "CorpWarDeclaredMsg",

    /**
     * value: "CorpWarDeclaredV2"
     * @const
     */
    CorpWarDeclaredV2: "CorpWarDeclaredV2",

    /**
     * value: "CorpWarFightingLegalMsg"
     * @const
     */
    CorpWarFightingLegalMsg: "CorpWarFightingLegalMsg",

    /**
     * value: "CorpWarInvalidatedMsg"
     * @const
     */
    CorpWarInvalidatedMsg: "CorpWarInvalidatedMsg",

    /**
     * value: "CorpWarRetractedMsg"
     * @const
     */
    CorpWarRetractedMsg: "CorpWarRetractedMsg",

    /**
     * value: "CorpWarSurrenderMsg"
     * @const
     */
    CorpWarSurrenderMsg: "CorpWarSurrenderMsg",

    /**
     * value: "CustomsMsg"
     * @const
     */
    CustomsMsg: "CustomsMsg",

    /**
     * value: "DeclareWar"
     * @const
     */
    DeclareWar: "DeclareWar",

    /**
     * value: "DistrictAttacked"
     * @const
     */
    DistrictAttacked: "DistrictAttacked",

    /**
     * value: "DustAppAcceptedMsg"
     * @const
     */
    DustAppAcceptedMsg: "DustAppAcceptedMsg",

    /**
     * value: "ESSMainBankLink"
     * @const
     */
    ESSMainBankLink: "ESSMainBankLink",

    /**
     * value: "EntosisCaptureStarted"
     * @const
     */
    EntosisCaptureStarted: "EntosisCaptureStarted",

    /**
     * value: "ExpertSystemExpired"
     * @const
     */
    ExpertSystemExpired: "ExpertSystemExpired",

    /**
     * value: "ExpertSystemExpiryImminent"
     * @const
     */
    ExpertSystemExpiryImminent: "ExpertSystemExpiryImminent",

    /**
     * value: "FWAllianceKickMsg"
     * @const
     */
    FWAllianceKickMsg: "FWAllianceKickMsg",

    /**
     * value: "FWAllianceWarningMsg"
     * @const
     */
    FWAllianceWarningMsg: "FWAllianceWarningMsg",

    /**
     * value: "FWCharKickMsg"
     * @const
     */
    FWCharKickMsg: "FWCharKickMsg",

    /**
     * value: "FWCharRankGainMsg"
     * @const
     */
    FWCharRankGainMsg: "FWCharRankGainMsg",

    /**
     * value: "FWCharRankLossMsg"
     * @const
     */
    FWCharRankLossMsg: "FWCharRankLossMsg",

    /**
     * value: "FWCharWarningMsg"
     * @const
     */
    FWCharWarningMsg: "FWCharWarningMsg",

    /**
     * value: "FWCorpJoinMsg"
     * @const
     */
    FWCorpJoinMsg: "FWCorpJoinMsg",

    /**
     * value: "FWCorpKickMsg"
     * @const
     */
    FWCorpKickMsg: "FWCorpKickMsg",

    /**
     * value: "FWCorpLeaveMsg"
     * @const
     */
    FWCorpLeaveMsg: "FWCorpLeaveMsg",

    /**
     * value: "FWCorpWarningMsg"
     * @const
     */
    FWCorpWarningMsg: "FWCorpWarningMsg",

    /**
     * value: "FacWarCorpJoinRequestMsg"
     * @const
     */
    FacWarCorpJoinRequestMsg: "FacWarCorpJoinRequestMsg",

    /**
     * value: "FacWarCorpJoinWithdrawMsg"
     * @const
     */
    FacWarCorpJoinWithdrawMsg: "FacWarCorpJoinWithdrawMsg",

    /**
     * value: "FacWarCorpLeaveRequestMsg"
     * @const
     */
    FacWarCorpLeaveRequestMsg: "FacWarCorpLeaveRequestMsg",

    /**
     * value: "FacWarCorpLeaveWithdrawMsg"
     * @const
     */
    FacWarCorpLeaveWithdrawMsg: "FacWarCorpLeaveWithdrawMsg",

    /**
     * value: "FacWarLPDisqualifiedEvent"
     * @const
     */
    FacWarLPDisqualifiedEvent: "FacWarLPDisqualifiedEvent",

    /**
     * value: "FacWarLPDisqualifiedKill"
     * @const
     */
    FacWarLPDisqualifiedKill: "FacWarLPDisqualifiedKill",

    /**
     * value: "FacWarLPPayoutEvent"
     * @const
     */
    FacWarLPPayoutEvent: "FacWarLPPayoutEvent",

    /**
     * value: "FacWarLPPayoutKill"
     * @const
     */
    FacWarLPPayoutKill: "FacWarLPPayoutKill",

    /**
     * value: "GameTimeAdded"
     * @const
     */
    GameTimeAdded: "GameTimeAdded",

    /**
     * value: "GameTimeReceived"
     * @const
     */
    GameTimeReceived: "GameTimeReceived",

    /**
     * value: "GameTimeSent"
     * @const
     */
    GameTimeSent: "GameTimeSent",

    /**
     * value: "GiftReceived"
     * @const
     */
    GiftReceived: "GiftReceived",

    /**
     * value: "IHubDestroyedByBillFailure"
     * @const
     */
    IHubDestroyedByBillFailure: "IHubDestroyedByBillFailure",

    /**
     * value: "IncursionCompletedMsg"
     * @const
     */
    IncursionCompletedMsg: "IncursionCompletedMsg",

    /**
     * value: "IndustryOperationFinished"
     * @const
     */
    IndustryOperationFinished: "IndustryOperationFinished",

    /**
     * value: "IndustryTeamAuctionLost"
     * @const
     */
    IndustryTeamAuctionLost: "IndustryTeamAuctionLost",

    /**
     * value: "IndustryTeamAuctionWon"
     * @const
     */
    IndustryTeamAuctionWon: "IndustryTeamAuctionWon",

    /**
     * value: "InfrastructureHubBillAboutToExpire"
     * @const
     */
    InfrastructureHubBillAboutToExpire: "InfrastructureHubBillAboutToExpire",

    /**
     * value: "InsuranceExpirationMsg"
     * @const
     */
    InsuranceExpirationMsg: "InsuranceExpirationMsg",

    /**
     * value: "InsuranceFirstShipMsg"
     * @const
     */
    InsuranceFirstShipMsg: "InsuranceFirstShipMsg",

    /**
     * value: "InsuranceInvalidatedMsg"
     * @const
     */
    InsuranceInvalidatedMsg: "InsuranceInvalidatedMsg",

    /**
     * value: "InsuranceIssuedMsg"
     * @const
     */
    InsuranceIssuedMsg: "InsuranceIssuedMsg",

    /**
     * value: "InsurancePayoutMsg"
     * @const
     */
    InsurancePayoutMsg: "InsurancePayoutMsg",

    /**
     * value: "InvasionCompletedMsg"
     * @const
     */
    InvasionCompletedMsg: "InvasionCompletedMsg",

    /**
     * value: "InvasionSystemLogin"
     * @const
     */
    InvasionSystemLogin: "InvasionSystemLogin",

    /**
     * value: "InvasionSystemStart"
     * @const
     */
    InvasionSystemStart: "InvasionSystemStart",

    /**
     * value: "JumpCloneDeletedMsg1"
     * @const
     */
    JumpCloneDeletedMsg1: "JumpCloneDeletedMsg1",

    /**
     * value: "JumpCloneDeletedMsg2"
     * @const
     */
    JumpCloneDeletedMsg2: "JumpCloneDeletedMsg2",

    /**
     * value: "KillReportFinalBlow"
     * @const
     */
    KillReportFinalBlow: "KillReportFinalBlow",

    /**
     * value: "KillReportVictim"
     * @const
     */
    KillReportVictim: "KillReportVictim",

    /**
     * value: "KillRightAvailable"
     * @const
     */
    KillRightAvailable: "KillRightAvailable",

    /**
     * value: "KillRightAvailableOpen"
     * @const
     */
    KillRightAvailableOpen: "KillRightAvailableOpen",

    /**
     * value: "KillRightEarned"
     * @const
     */
    KillRightEarned: "KillRightEarned",

    /**
     * value: "KillRightUnavailable"
     * @const
     */
    KillRightUnavailable: "KillRightUnavailable",

    /**
     * value: "KillRightUnavailableOpen"
     * @const
     */
    KillRightUnavailableOpen: "KillRightUnavailableOpen",

    /**
     * value: "KillRightUsed"
     * @const
     */
    KillRightUsed: "KillRightUsed",

    /**
     * value: "LocateCharMsg"
     * @const
     */
    LocateCharMsg: "LocateCharMsg",

    /**
     * value: "MadeWarMutual"
     * @const
     */
    MadeWarMutual: "MadeWarMutual",

    /**
     * value: "MercOfferRetractedMsg"
     * @const
     */
    MercOfferRetractedMsg: "MercOfferRetractedMsg",

    /**
     * value: "MercOfferedNegotiationMsg"
     * @const
     */
    MercOfferedNegotiationMsg: "MercOfferedNegotiationMsg",

    /**
     * value: "MissionCanceledTriglavian"
     * @const
     */
    MissionCanceledTriglavian: "MissionCanceledTriglavian",

    /**
     * value: "MissionOfferExpirationMsg"
     * @const
     */
    MissionOfferExpirationMsg: "MissionOfferExpirationMsg",

    /**
     * value: "MissionTimeoutMsg"
     * @const
     */
    MissionTimeoutMsg: "MissionTimeoutMsg",

    /**
     * value: "MoonminingAutomaticFracture"
     * @const
     */
    MoonminingAutomaticFracture: "MoonminingAutomaticFracture",

    /**
     * value: "MoonminingExtractionCancelled"
     * @const
     */
    MoonminingExtractionCancelled: "MoonminingExtractionCancelled",

    /**
     * value: "MoonminingExtractionFinished"
     * @const
     */
    MoonminingExtractionFinished: "MoonminingExtractionFinished",

    /**
     * value: "MoonminingExtractionStarted"
     * @const
     */
    MoonminingExtractionStarted: "MoonminingExtractionStarted",

    /**
     * value: "MoonminingLaserFired"
     * @const
     */
    MoonminingLaserFired: "MoonminingLaserFired",

    /**
     * value: "MutualWarExpired"
     * @const
     */
    MutualWarExpired: "MutualWarExpired",

    /**
     * value: "MutualWarInviteAccepted"
     * @const
     */
    MutualWarInviteAccepted: "MutualWarInviteAccepted",

    /**
     * value: "MutualWarInviteRejected"
     * @const
     */
    MutualWarInviteRejected: "MutualWarInviteRejected",

    /**
     * value: "MutualWarInviteSent"
     * @const
     */
    MutualWarInviteSent: "MutualWarInviteSent",

    /**
     * value: "NPCStandingsGained"
     * @const
     */
    NPCStandingsGained: "NPCStandingsGained",

    /**
     * value: "NPCStandingsLost"
     * @const
     */
    NPCStandingsLost: "NPCStandingsLost",

    /**
     * value: "OfferToAllyRetracted"
     * @const
     */
    OfferToAllyRetracted: "OfferToAllyRetracted",

    /**
     * value: "OfferedSurrender"
     * @const
     */
    OfferedSurrender: "OfferedSurrender",

    /**
     * value: "OfferedToAlly"
     * @const
     */
    OfferedToAlly: "OfferedToAlly",

    /**
     * value: "OfficeLeaseCanceledInsufficientStandings"
     * @const
     */
    OfficeLeaseCanceledInsufficientStandings: "OfficeLeaseCanceledInsufficientStandings",

    /**
     * value: "OldLscMessages"
     * @const
     */
    OldLscMessages: "OldLscMessages",

    /**
     * value: "OperationFinished"
     * @const
     */
    OperationFinished: "OperationFinished",

    /**
     * value: "OrbitalAttacked"
     * @const
     */
    OrbitalAttacked: "OrbitalAttacked",

    /**
     * value: "OrbitalReinforced"
     * @const
     */
    OrbitalReinforced: "OrbitalReinforced",

    /**
     * value: "OwnershipTransferred"
     * @const
     */
    OwnershipTransferred: "OwnershipTransferred",

    /**
     * value: "RaffleCreated"
     * @const
     */
    RaffleCreated: "RaffleCreated",

    /**
     * value: "RaffleExpired"
     * @const
     */
    RaffleExpired: "RaffleExpired",

    /**
     * value: "RaffleFinished"
     * @const
     */
    RaffleFinished: "RaffleFinished",

    /**
     * value: "ReimbursementMsg"
     * @const
     */
    ReimbursementMsg: "ReimbursementMsg",

    /**
     * value: "ResearchMissionAvailableMsg"
     * @const
     */
    ResearchMissionAvailableMsg: "ResearchMissionAvailableMsg",

    /**
     * value: "RetractsWar"
     * @const
     */
    RetractsWar: "RetractsWar",

    /**
     * value: "SeasonalChallengeCompleted"
     * @const
     */
    SeasonalChallengeCompleted: "SeasonalChallengeCompleted",

    /**
     * value: "SovAllClaimAquiredMsg"
     * @const
     */
    SovAllClaimAquiredMsg: "SovAllClaimAquiredMsg",

    /**
     * value: "SovAllClaimLostMsg"
     * @const
     */
    SovAllClaimLostMsg: "SovAllClaimLostMsg",

    /**
     * value: "SovCommandNodeEventStarted"
     * @const
     */
    SovCommandNodeEventStarted: "SovCommandNodeEventStarted",

    /**
     * value: "SovCorpBillLateMsg"
     * @const
     */
    SovCorpBillLateMsg: "SovCorpBillLateMsg",

    /**
     * value: "SovCorpClaimFailMsg"
     * @const
     */
    SovCorpClaimFailMsg: "SovCorpClaimFailMsg",

    /**
     * value: "SovDisruptorMsg"
     * @const
     */
    SovDisruptorMsg: "SovDisruptorMsg",

    /**
     * value: "SovStationEnteredFreeport"
     * @const
     */
    SovStationEnteredFreeport: "SovStationEnteredFreeport",

    /**
     * value: "SovStructureDestroyed"
     * @const
     */
    SovStructureDestroyed: "SovStructureDestroyed",

    /**
     * value: "SovStructureReinforced"
     * @const
     */
    SovStructureReinforced: "SovStructureReinforced",

    /**
     * value: "SovStructureSelfDestructCancel"
     * @const
     */
    SovStructureSelfDestructCancel: "SovStructureSelfDestructCancel",

    /**
     * value: "SovStructureSelfDestructFinished"
     * @const
     */
    SovStructureSelfDestructFinished: "SovStructureSelfDestructFinished",

    /**
     * value: "SovStructureSelfDestructRequested"
     * @const
     */
    SovStructureSelfDestructRequested: "SovStructureSelfDestructRequested",

    /**
     * value: "SovereigntyIHDamageMsg"
     * @const
     */
    SovereigntyIHDamageMsg: "SovereigntyIHDamageMsg",

    /**
     * value: "SovereigntySBUDamageMsg"
     * @const
     */
    SovereigntySBUDamageMsg: "SovereigntySBUDamageMsg",

    /**
     * value: "SovereigntyTCUDamageMsg"
     * @const
     */
    SovereigntyTCUDamageMsg: "SovereigntyTCUDamageMsg",

    /**
     * value: "StationAggressionMsg1"
     * @const
     */
    StationAggressionMsg1: "StationAggressionMsg1",

    /**
     * value: "StationAggressionMsg2"
     * @const
     */
    StationAggressionMsg2: "StationAggressionMsg2",

    /**
     * value: "StationConquerMsg"
     * @const
     */
    StationConquerMsg: "StationConquerMsg",

    /**
     * value: "StationServiceDisabled"
     * @const
     */
    StationServiceDisabled: "StationServiceDisabled",

    /**
     * value: "StationServiceEnabled"
     * @const
     */
    StationServiceEnabled: "StationServiceEnabled",

    /**
     * value: "StationStateChangeMsg"
     * @const
     */
    StationStateChangeMsg: "StationStateChangeMsg",

    /**
     * value: "StoryLineMissionAvailableMsg"
     * @const
     */
    StoryLineMissionAvailableMsg: "StoryLineMissionAvailableMsg",

    /**
     * value: "StructureAnchoring"
     * @const
     */
    StructureAnchoring: "StructureAnchoring",

    /**
     * value: "StructureCourierContractChanged"
     * @const
     */
    StructureCourierContractChanged: "StructureCourierContractChanged",

    /**
     * value: "StructureDestroyed"
     * @const
     */
    StructureDestroyed: "StructureDestroyed",

    /**
     * value: "StructureFuelAlert"
     * @const
     */
    StructureFuelAlert: "StructureFuelAlert",

    /**
     * value: "StructureImpendingAbandonmentAssetsAtRisk"
     * @const
     */
    StructureImpendingAbandonmentAssetsAtRisk: "StructureImpendingAbandonmentAssetsAtRisk",

    /**
     * value: "StructureItemsDelivered"
     * @const
     */
    StructureItemsDelivered: "StructureItemsDelivered",

    /**
     * value: "StructureItemsMovedToSafety"
     * @const
     */
    StructureItemsMovedToSafety: "StructureItemsMovedToSafety",

    /**
     * value: "StructureLostArmor"
     * @const
     */
    StructureLostArmor: "StructureLostArmor",

    /**
     * value: "StructureLostShields"
     * @const
     */
    StructureLostShields: "StructureLostShields",

    /**
     * value: "StructureOnline"
     * @const
     */
    StructureOnline: "StructureOnline",

    /**
     * value: "StructureServicesOffline"
     * @const
     */
    StructureServicesOffline: "StructureServicesOffline",

    /**
     * value: "StructureUnanchoring"
     * @const
     */
    StructureUnanchoring: "StructureUnanchoring",

    /**
     * value: "StructureUnderAttack"
     * @const
     */
    StructureUnderAttack: "StructureUnderAttack",

    /**
     * value: "StructureWentHighPower"
     * @const
     */
    StructureWentHighPower: "StructureWentHighPower",

    /**
     * value: "StructureWentLowPower"
     * @const
     */
    StructureWentLowPower: "StructureWentLowPower",

    /**
     * value: "StructuresJobsCancelled"
     * @const
     */
    StructuresJobsCancelled: "StructuresJobsCancelled",

    /**
     * value: "StructuresJobsPaused"
     * @const
     */
    StructuresJobsPaused: "StructuresJobsPaused",

    /**
     * value: "StructuresReinforcementChanged"
     * @const
     */
    StructuresReinforcementChanged: "StructuresReinforcementChanged",

    /**
     * value: "TowerAlertMsg"
     * @const
     */
    TowerAlertMsg: "TowerAlertMsg",

    /**
     * value: "TowerResourceAlertMsg"
     * @const
     */
    TowerResourceAlertMsg: "TowerResourceAlertMsg",

    /**
     * value: "TransactionReversalMsg"
     * @const
     */
    TransactionReversalMsg: "TransactionReversalMsg",

    /**
     * value: "TutorialMsg"
     * @const
     */
    TutorialMsg: "TutorialMsg",

    /**
     * value: "WarAdopted "
     * @const
     */
    WarAdopted_: "WarAdopted ",

    /**
     * value: "WarAllyInherited"
     * @const
     */
    WarAllyInherited: "WarAllyInherited",

    /**
     * value: "WarAllyOfferDeclinedMsg"
     * @const
     */
    WarAllyOfferDeclinedMsg: "WarAllyOfferDeclinedMsg",

    /**
     * value: "WarConcordInvalidates"
     * @const
     */
    WarConcordInvalidates: "WarConcordInvalidates",

    /**
     * value: "WarDeclared"
     * @const
     */
    WarDeclared: "WarDeclared",

    /**
     * value: "WarEndedHqSecurityDrop"
     * @const
     */
    WarEndedHqSecurityDrop: "WarEndedHqSecurityDrop",

    /**
     * value: "WarHQRemovedFromSpace"
     * @const
     */
    WarHQRemovedFromSpace: "WarHQRemovedFromSpace",

    /**
     * value: "WarInherited"
     * @const
     */
    WarInherited: "WarInherited",

    /**
     * value: "WarInvalid"
     * @const
     */
    WarInvalid: "WarInvalid",

    /**
     * value: "WarRetracted"
     * @const
     */
    WarRetracted: "WarRetracted",

    /**
     * value: "WarRetractedByConcord"
     * @const
     */
    WarRetractedByConcord: "WarRetractedByConcord",

    /**
     * value: "WarSurrenderDeclinedMsg"
     * @const
     */
    WarSurrenderDeclinedMsg: "WarSurrenderDeclinedMsg",

    /**
     * value: "WarSurrenderOfferMsg"
     * @const
     */
    WarSurrenderOfferMsg: "WarSurrenderOfferMsg"
  };

  return exports;

}));
