/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdPlanetsPlanetIdContent', 'model/GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails', 'model/GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdPlanetsPlanetIdContent'), require('./GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails'), require('./GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCharactersCharacterIdPlanetsPlanetIdPin = factory(root.EveApi.ApiClient, root.EveApi.GetCharactersCharacterIdPlanetsPlanetIdContent, root.EveApi.GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails, root.EveApi.GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails);
  }
}(this, function(ApiClient, GetCharactersCharacterIdPlanetsPlanetIdContent, GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails, GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails) {
  'use strict';

  /**
   * The GetCharactersCharacterIdPlanetsPlanetIdPin model module.
   * @module model/GetCharactersCharacterIdPlanetsPlanetIdPin
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdPlanetsPlanetIdPin</code>.
   * pin object
   * @alias module:model/GetCharactersCharacterIdPlanetsPlanetIdPin
   * @class
   * @param latitude {Number} latitude number
   * @param longitude {Number} longitude number
   * @param pin_id {Number} pin_id integer
   * @param type_id {Number} type_id integer
   */
  var exports = function(latitude, longitude, pin_id, type_id) {
    this.latitude = latitude;
    this.longitude = longitude;
    this.pin_id = pin_id;
    this.type_id = type_id;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdPlanetsPlanetIdPin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdPlanetsPlanetIdPin} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdPlanetsPlanetIdPin} The populated <code>GetCharactersCharacterIdPlanetsPlanetIdPin</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contents'))
        obj.contents = ApiClient.convertToType(data['contents'], [GetCharactersCharacterIdPlanetsPlanetIdContent]);
      if (data.hasOwnProperty('expiry_time'))
        obj.expiry_time = ApiClient.convertToType(data['expiry_time'], 'Date');
      if (data.hasOwnProperty('extractor_details'))
        obj.extractor_details = GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails.constructFromObject(data['extractor_details']);
      if (data.hasOwnProperty('factory_details'))
        obj.factory_details = GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails.constructFromObject(data['factory_details']);
      if (data.hasOwnProperty('install_time'))
        obj.install_time = ApiClient.convertToType(data['install_time'], 'Date');
      if (data.hasOwnProperty('last_cycle_start'))
        obj.last_cycle_start = ApiClient.convertToType(data['last_cycle_start'], 'Date');
      if (data.hasOwnProperty('latitude'))
        obj.latitude = ApiClient.convertToType(data['latitude'], 'Number');
      if (data.hasOwnProperty('longitude'))
        obj.longitude = ApiClient.convertToType(data['longitude'], 'Number');
      if (data.hasOwnProperty('pin_id'))
        obj.pin_id = ApiClient.convertToType(data['pin_id'], 'Number');
      if (data.hasOwnProperty('schematic_id'))
        obj.schematic_id = ApiClient.convertToType(data['schematic_id'], 'Number');
      if (data.hasOwnProperty('type_id'))
        obj.type_id = ApiClient.convertToType(data['type_id'], 'Number');
    }
    return obj;
  }

  /**
   * contents array
   * @member {Array.<module:model/GetCharactersCharacterIdPlanetsPlanetIdContent>} contents
   */
  exports.prototype.contents = undefined;

  /**
   * expiry_time string
   * @member {Date} expiry_time
   */
  exports.prototype.expiry_time = undefined;

  /**
   * @member {module:model/GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails} extractor_details
   */
  exports.prototype.extractor_details = undefined;

  /**
   * @member {module:model/GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails} factory_details
   */
  exports.prototype.factory_details = undefined;

  /**
   * install_time string
   * @member {Date} install_time
   */
  exports.prototype.install_time = undefined;

  /**
   * last_cycle_start string
   * @member {Date} last_cycle_start
   */
  exports.prototype.last_cycle_start = undefined;

  /**
   * latitude number
   * @member {Number} latitude
   */
  exports.prototype.latitude = undefined;

  /**
   * longitude number
   * @member {Number} longitude
   */
  exports.prototype.longitude = undefined;

  /**
   * pin_id integer
   * @member {Number} pin_id
   */
  exports.prototype.pin_id = undefined;

  /**
   * schematic_id integer
   * @member {Number} schematic_id
   */
  exports.prototype.schematic_id = undefined;

  /**
   * type_id integer
   * @member {Number} type_id
   */
  exports.prototype.type_id = undefined;


  return exports;

}));
