/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails model module.
   * @module model/GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails</code>.
   * factory_details object
   * @alias module:model/GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails
   * @class
   * @param schematic_id {Number} schematic_id integer
   */
  var exports = function(schematic_id) {
    this.schematic_id = schematic_id;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails} The populated <code>GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('schematic_id'))
        obj.schematic_id = ApiClient.convertToType(data['schematic_id'], 'Number');
    }
    return obj;
  }

  /**
   * schematic_id integer
   * @member {Number} schematic_id
   */
  exports.prototype.schematic_id = undefined;


  return exports;

}));
