/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetCorporationCorporationIdMiningObserversObserverId200Ok = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetCorporationCorporationIdMiningObserversObserverId200Ok model module.
   * @module model/GetCorporationCorporationIdMiningObserversObserverId200Ok
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetCorporationCorporationIdMiningObserversObserverId200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCorporationCorporationIdMiningObserversObserverId200Ok
   * @class
   * @param character_id {Number} The character that did the mining 
   * @param last_updated {Date} last_updated string
   * @param quantity {Number} quantity integer
   * @param recorded_corporation_id {Number} The corporation id of the character at the time data was recorded. 
   * @param type_id {Number} type_id integer
   */
  var exports = function(character_id, last_updated, quantity, recorded_corporation_id, type_id) {
    this.character_id = character_id;
    this.last_updated = last_updated;
    this.quantity = quantity;
    this.recorded_corporation_id = recorded_corporation_id;
    this.type_id = type_id;
  };

  /**
   * Constructs a <code>GetCorporationCorporationIdMiningObserversObserverId200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationCorporationIdMiningObserversObserverId200Ok} obj Optional instance to populate.
   * @return {module:model/GetCorporationCorporationIdMiningObserversObserverId200Ok} The populated <code>GetCorporationCorporationIdMiningObserversObserverId200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('character_id'))
        obj.character_id = ApiClient.convertToType(data['character_id'], 'Number');
      if (data.hasOwnProperty('last_updated'))
        obj.last_updated = ApiClient.convertToType(data['last_updated'], 'Date');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('recorded_corporation_id'))
        obj.recorded_corporation_id = ApiClient.convertToType(data['recorded_corporation_id'], 'Number');
      if (data.hasOwnProperty('type_id'))
        obj.type_id = ApiClient.convertToType(data['type_id'], 'Number');
    }
    return obj;
  }

  /**
   * The character that did the mining 
   * @member {Number} character_id
   */
  exports.prototype.character_id = undefined;

  /**
   * last_updated string
   * @member {Date} last_updated
   */
  exports.prototype.last_updated = undefined;

  /**
   * quantity integer
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * The corporation id of the character at the time data was recorded. 
   * @member {Number} recorded_corporation_id
   */
  exports.prototype.recorded_corporation_id = undefined;

  /**
   * type_id integer
   * @member {Number} type_id
   */
  exports.prototype.type_id = undefined;


  return exports;

}));
