/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetFwLeaderboardsCharactersKills', 'model/GetFwLeaderboardsCharactersVictoryPoints'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetFwLeaderboardsCharactersKills'), require('./GetFwLeaderboardsCharactersVictoryPoints'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetFwLeaderboardsCharactersOk = factory(root.EveApi.ApiClient, root.EveApi.GetFwLeaderboardsCharactersKills, root.EveApi.GetFwLeaderboardsCharactersVictoryPoints);
  }
}(this, function(ApiClient, GetFwLeaderboardsCharactersKills, GetFwLeaderboardsCharactersVictoryPoints) {
  'use strict';

  /**
   * The GetFwLeaderboardsCharactersOk model module.
   * @module model/GetFwLeaderboardsCharactersOk
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetFwLeaderboardsCharactersOk</code>.
   * 200 ok object
   * @alias module:model/GetFwLeaderboardsCharactersOk
   * @class
   * @param kills {module:model/GetFwLeaderboardsCharactersKills} 
   * @param victory_points {module:model/GetFwLeaderboardsCharactersVictoryPoints} 
   */
  var exports = function(kills, victory_points) {
    this.kills = kills;
    this.victory_points = victory_points;
  };

  /**
   * Constructs a <code>GetFwLeaderboardsCharactersOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetFwLeaderboardsCharactersOk} obj Optional instance to populate.
   * @return {module:model/GetFwLeaderboardsCharactersOk} The populated <code>GetFwLeaderboardsCharactersOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('kills'))
        obj.kills = GetFwLeaderboardsCharactersKills.constructFromObject(data['kills']);
      if (data.hasOwnProperty('victory_points'))
        obj.victory_points = GetFwLeaderboardsCharactersVictoryPoints.constructFromObject(data['victory_points']);
    }
    return obj;
  }

  /**
   * @member {module:model/GetFwLeaderboardsCharactersKills} kills
   */
  exports.prototype.kills = undefined;

  /**
   * @member {module:model/GetFwLeaderboardsCharactersVictoryPoints} victory_points
   */
  exports.prototype.victory_points = undefined;


  return exports;

}));
