/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetFwLeaderboardsActiveTotalActiveTotal', 'model/GetFwLeaderboardsLastWeekLastWeek', 'model/GetFwLeaderboardsYesterdayYesterday'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetFwLeaderboardsActiveTotalActiveTotal'), require('./GetFwLeaderboardsLastWeekLastWeek'), require('./GetFwLeaderboardsYesterdayYesterday'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetFwLeaderboardsKills = factory(root.EveApi.ApiClient, root.EveApi.GetFwLeaderboardsActiveTotalActiveTotal, root.EveApi.GetFwLeaderboardsLastWeekLastWeek, root.EveApi.GetFwLeaderboardsYesterdayYesterday);
  }
}(this, function(ApiClient, GetFwLeaderboardsActiveTotalActiveTotal, GetFwLeaderboardsLastWeekLastWeek, GetFwLeaderboardsYesterdayYesterday) {
  'use strict';

  /**
   * The GetFwLeaderboardsKills model module.
   * @module model/GetFwLeaderboardsKills
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetFwLeaderboardsKills</code>.
   * Top 4 rankings of factions by number of kills from yesterday, last week and in total
   * @alias module:model/GetFwLeaderboardsKills
   * @class
   * @param active_total {Array.<module:model/GetFwLeaderboardsActiveTotalActiveTotal>} Top 4 ranking of factions active in faction warfare by total kills. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
   * @param last_week {Array.<module:model/GetFwLeaderboardsLastWeekLastWeek>} Top 4 ranking of factions by kills in the past week
   * @param yesterday {Array.<module:model/GetFwLeaderboardsYesterdayYesterday>} Top 4 ranking of factions by kills in the past day
   */
  var exports = function(active_total, last_week, yesterday) {
    this.active_total = active_total;
    this.last_week = last_week;
    this.yesterday = yesterday;
  };

  /**
   * Constructs a <code>GetFwLeaderboardsKills</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetFwLeaderboardsKills} obj Optional instance to populate.
   * @return {module:model/GetFwLeaderboardsKills} The populated <code>GetFwLeaderboardsKills</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('active_total'))
        obj.active_total = ApiClient.convertToType(data['active_total'], [GetFwLeaderboardsActiveTotalActiveTotal]);
      if (data.hasOwnProperty('last_week'))
        obj.last_week = ApiClient.convertToType(data['last_week'], [GetFwLeaderboardsLastWeekLastWeek]);
      if (data.hasOwnProperty('yesterday'))
        obj.yesterday = ApiClient.convertToType(data['yesterday'], [GetFwLeaderboardsYesterdayYesterday]);
    }
    return obj;
  }

  /**
   * Top 4 ranking of factions active in faction warfare by total kills. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
   * @member {Array.<module:model/GetFwLeaderboardsActiveTotalActiveTotal>} active_total
   */
  exports.prototype.active_total = undefined;

  /**
   * Top 4 ranking of factions by kills in the past week
   * @member {Array.<module:model/GetFwLeaderboardsLastWeekLastWeek>} last_week
   */
  exports.prototype.last_week = undefined;

  /**
   * Top 4 ranking of factions by kills in the past day
   * @member {Array.<module:model/GetFwLeaderboardsYesterdayYesterday>} yesterday
   */
  exports.prototype.yesterday = undefined;


  return exports;

}));
