/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetUniverseStarsStarIdOk = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetUniverseStarsStarIdOk model module.
   * @module model/GetUniverseStarsStarIdOk
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetUniverseStarsStarIdOk</code>.
   * 200 ok object
   * @alias module:model/GetUniverseStarsStarIdOk
   * @class
   * @param age {Number} Age of star in years
   * @param luminosity {Number} luminosity number
   * @param name {String} name string
   * @param radius {Number} radius integer
   * @param solar_system_id {Number} solar_system_id integer
   * @param spectral_class {module:model/GetUniverseStarsStarIdOk.SpectralClassEnum} spectral_class string
   * @param temperature {Number} temperature integer
   * @param type_id {Number} type_id integer
   */
  var exports = function(age, luminosity, name, radius, solar_system_id, spectral_class, temperature, type_id) {
    this.age = age;
    this.luminosity = luminosity;
    this.name = name;
    this.radius = radius;
    this.solar_system_id = solar_system_id;
    this.spectral_class = spectral_class;
    this.temperature = temperature;
    this.type_id = type_id;
  };

  /**
   * Constructs a <code>GetUniverseStarsStarIdOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUniverseStarsStarIdOk} obj Optional instance to populate.
   * @return {module:model/GetUniverseStarsStarIdOk} The populated <code>GetUniverseStarsStarIdOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('age'))
        obj.age = ApiClient.convertToType(data['age'], 'Number');
      if (data.hasOwnProperty('luminosity'))
        obj.luminosity = ApiClient.convertToType(data['luminosity'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('radius'))
        obj.radius = ApiClient.convertToType(data['radius'], 'Number');
      if (data.hasOwnProperty('solar_system_id'))
        obj.solar_system_id = ApiClient.convertToType(data['solar_system_id'], 'Number');
      if (data.hasOwnProperty('spectral_class'))
        obj.spectral_class = ApiClient.convertToType(data['spectral_class'], 'String');
      if (data.hasOwnProperty('temperature'))
        obj.temperature = ApiClient.convertToType(data['temperature'], 'Number');
      if (data.hasOwnProperty('type_id'))
        obj.type_id = ApiClient.convertToType(data['type_id'], 'Number');
    }
    return obj;
  }

  /**
   * Age of star in years
   * @member {Number} age
   */
  exports.prototype.age = undefined;

  /**
   * luminosity number
   * @member {Number} luminosity
   */
  exports.prototype.luminosity = undefined;

  /**
   * name string
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * radius integer
   * @member {Number} radius
   */
  exports.prototype.radius = undefined;

  /**
   * solar_system_id integer
   * @member {Number} solar_system_id
   */
  exports.prototype.solar_system_id = undefined;

  /**
   * spectral_class string
   * @member {module:model/GetUniverseStarsStarIdOk.SpectralClassEnum} spectral_class
   */
  exports.prototype.spectral_class = undefined;

  /**
   * temperature integer
   * @member {Number} temperature
   */
  exports.prototype.temperature = undefined;

  /**
   * type_id integer
   * @member {Number} type_id
   */
  exports.prototype.type_id = undefined;



  /**
   * Allowed values for the <code>spectral_class</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SpectralClassEnum = {
    /**
     * value: "K2 V"
     * @const
     */
    K2_V: "K2 V",

    /**
     * value: "K4 V"
     * @const
     */
    K4_V: "K4 V",

    /**
     * value: "G2 V"
     * @const
     */
    G2_V: "G2 V",

    /**
     * value: "G8 V"
     * @const
     */
    G8_V: "G8 V",

    /**
     * value: "M7 V"
     * @const
     */
    M7_V: "M7 V",

    /**
     * value: "K7 V"
     * @const
     */
    K7_V: "K7 V",

    /**
     * value: "M2 V"
     * @const
     */
    M2_V: "M2 V",

    /**
     * value: "K5 V"
     * @const
     */
    K5_V: "K5 V",

    /**
     * value: "M3 V"
     * @const
     */
    M3_V: "M3 V",

    /**
     * value: "G0 V"
     * @const
     */
    G0_V: "G0 V",

    /**
     * value: "G7 V"
     * @const
     */
    G7_V: "G7 V",

    /**
     * value: "G3 V"
     * @const
     */
    G3_V: "G3 V",

    /**
     * value: "F9 V"
     * @const
     */
    F9_V: "F9 V",

    /**
     * value: "G5 V"
     * @const
     */
    G5_V: "G5 V",

    /**
     * value: "F6 V"
     * @const
     */
    F6_V: "F6 V",

    /**
     * value: "K8 V"
     * @const
     */
    K8_V: "K8 V",

    /**
     * value: "K9 V"
     * @const
     */
    K9_V: "K9 V",

    /**
     * value: "K6 V"
     * @const
     */
    K6_V: "K6 V",

    /**
     * value: "G9 V"
     * @const
     */
    G9_V: "G9 V",

    /**
     * value: "G6 V"
     * @const
     */
    G6_V: "G6 V",

    /**
     * value: "G4 VI"
     * @const
     */
    G4_VI: "G4 VI",

    /**
     * value: "G4 V"
     * @const
     */
    G4_V: "G4 V",

    /**
     * value: "F8 V"
     * @const
     */
    F8_V: "F8 V",

    /**
     * value: "F2 V"
     * @const
     */
    F2_V: "F2 V",

    /**
     * value: "F1 V"
     * @const
     */
    F1_V: "F1 V",

    /**
     * value: "K3 V"
     * @const
     */
    K3_V: "K3 V",

    /**
     * value: "F0 VI"
     * @const
     */
    F0_VI: "F0 VI",

    /**
     * value: "G1 VI"
     * @const
     */
    G1_VI: "G1 VI",

    /**
     * value: "G0 VI"
     * @const
     */
    G0_VI: "G0 VI",

    /**
     * value: "K1 V"
     * @const
     */
    K1_V: "K1 V",

    /**
     * value: "M4 V"
     * @const
     */
    M4_V: "M4 V",

    /**
     * value: "M1 V"
     * @const
     */
    M1_V: "M1 V",

    /**
     * value: "M6 V"
     * @const
     */
    M6_V: "M6 V",

    /**
     * value: "M0 V"
     * @const
     */
    M0_V: "M0 V",

    /**
     * value: "K2 IV"
     * @const
     */
    K2_IV: "K2 IV",

    /**
     * value: "G2 VI"
     * @const
     */
    G2_VI: "G2 VI",

    /**
     * value: "K0 V"
     * @const
     */
    K0_V: "K0 V",

    /**
     * value: "K5 IV"
     * @const
     */
    K5_IV: "K5 IV",

    /**
     * value: "F5 VI"
     * @const
     */
    F5_VI: "F5 VI",

    /**
     * value: "G6 VI"
     * @const
     */
    G6_VI: "G6 VI",

    /**
     * value: "F6 VI"
     * @const
     */
    F6_VI: "F6 VI",

    /**
     * value: "F2 IV"
     * @const
     */
    F2_IV: "F2 IV",

    /**
     * value: "G3 VI"
     * @const
     */
    G3_VI: "G3 VI",

    /**
     * value: "M8 V"
     * @const
     */
    M8_V: "M8 V",

    /**
     * value: "F1 VI"
     * @const
     */
    F1_VI: "F1 VI",

    /**
     * value: "K1 IV"
     * @const
     */
    K1_IV: "K1 IV",

    /**
     * value: "F7 V"
     * @const
     */
    F7_V: "F7 V",

    /**
     * value: "G5 VI"
     * @const
     */
    G5_VI: "G5 VI",

    /**
     * value: "M5 V"
     * @const
     */
    M5_V: "M5 V",

    /**
     * value: "G7 VI"
     * @const
     */
    G7_VI: "G7 VI",

    /**
     * value: "F5 V"
     * @const
     */
    F5_V: "F5 V",

    /**
     * value: "F4 VI"
     * @const
     */
    F4_VI: "F4 VI",

    /**
     * value: "F8 VI"
     * @const
     */
    F8_VI: "F8 VI",

    /**
     * value: "K3 IV"
     * @const
     */
    K3_IV: "K3 IV",

    /**
     * value: "F4 IV"
     * @const
     */
    F4_IV: "F4 IV",

    /**
     * value: "F0 V"
     * @const
     */
    F0_V: "F0 V",

    /**
     * value: "G7 IV"
     * @const
     */
    G7_IV: "G7 IV",

    /**
     * value: "G8 VI"
     * @const
     */
    G8_VI: "G8 VI",

    /**
     * value: "F2 VI"
     * @const
     */
    F2_VI: "F2 VI",

    /**
     * value: "F4 V"
     * @const
     */
    F4_V: "F4 V",

    /**
     * value: "F7 VI"
     * @const
     */
    F7_VI: "F7 VI",

    /**
     * value: "F3 V"
     * @const
     */
    F3_V: "F3 V",

    /**
     * value: "G1 V"
     * @const
     */
    G1_V: "G1 V",

    /**
     * value: "G9 VI"
     * @const
     */
    G9_VI: "G9 VI",

    /**
     * value: "F3 IV"
     * @const
     */
    F3_IV: "F3 IV",

    /**
     * value: "F9 VI"
     * @const
     */
    F9_VI: "F9 VI",

    /**
     * value: "M9 V"
     * @const
     */
    M9_V: "M9 V",

    /**
     * value: "K0 IV"
     * @const
     */
    K0_IV: "K0 IV",

    /**
     * value: "F1 IV"
     * @const
     */
    F1_IV: "F1 IV",

    /**
     * value: "G4 IV"
     * @const
     */
    G4_IV: "G4 IV",

    /**
     * value: "F3 VI"
     * @const
     */
    F3_VI: "F3 VI",

    /**
     * value: "K4 IV"
     * @const
     */
    K4_IV: "K4 IV",

    /**
     * value: "G5 IV"
     * @const
     */
    G5_IV: "G5 IV",

    /**
     * value: "G3 IV"
     * @const
     */
    G3_IV: "G3 IV",

    /**
     * value: "G1 IV"
     * @const
     */
    G1_IV: "G1 IV",

    /**
     * value: "K7 IV"
     * @const
     */
    K7_IV: "K7 IV",

    /**
     * value: "G0 IV"
     * @const
     */
    G0_IV: "G0 IV",

    /**
     * value: "K6 IV"
     * @const
     */
    K6_IV: "K6 IV",

    /**
     * value: "K9 IV"
     * @const
     */
    K9_IV: "K9 IV",

    /**
     * value: "G2 IV"
     * @const
     */
    G2_IV: "G2 IV",

    /**
     * value: "F9 IV"
     * @const
     */
    F9_IV: "F9 IV",

    /**
     * value: "F0 IV"
     * @const
     */
    F0_IV: "F0 IV",

    /**
     * value: "K8 IV"
     * @const
     */
    K8_IV: "K8 IV",

    /**
     * value: "G8 IV"
     * @const
     */
    G8_IV: "G8 IV",

    /**
     * value: "F6 IV"
     * @const
     */
    F6_IV: "F6 IV",

    /**
     * value: "F5 IV"
     * @const
     */
    F5_IV: "F5 IV",

    /**
     * value: "A0"
     * @const
     */
    A0: "A0",

    /**
     * value: "A0IV"
     * @const
     */
    A0IV: "A0IV",

    /**
     * value: "A0IV2"
     * @const
     */
    A0IV2: "A0IV2"
  };

  return exports;

}));
