/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetUniverseFactions200Ok = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetUniverseFactions200Ok model module.
   * @module model/GetUniverseFactions200Ok
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetUniverseFactions200Ok</code>.
   * 200 ok object
   * @alias module:model/GetUniverseFactions200Ok
   * @class
   * @param description {String} description string
   * @param faction_id {Number} faction_id integer
   * @param is_unique {Boolean} is_unique boolean
   * @param name {String} name string
   * @param size_factor {Number} size_factor number
   * @param station_count {Number} station_count integer
   * @param station_system_count {Number} station_system_count integer
   */
  var exports = function(description, faction_id, is_unique, name, size_factor, station_count, station_system_count) {
    this.description = description;
    this.faction_id = faction_id;
    this.is_unique = is_unique;
    this.name = name;
    this.size_factor = size_factor;
    this.station_count = station_count;
    this.station_system_count = station_system_count;
  };

  /**
   * Constructs a <code>GetUniverseFactions200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUniverseFactions200Ok} obj Optional instance to populate.
   * @return {module:model/GetUniverseFactions200Ok} The populated <code>GetUniverseFactions200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('corporation_id'))
        obj.corporation_id = ApiClient.convertToType(data['corporation_id'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('faction_id'))
        obj.faction_id = ApiClient.convertToType(data['faction_id'], 'Number');
      if (data.hasOwnProperty('is_unique'))
        obj.is_unique = ApiClient.convertToType(data['is_unique'], 'Boolean');
      if (data.hasOwnProperty('militia_corporation_id'))
        obj.militia_corporation_id = ApiClient.convertToType(data['militia_corporation_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('size_factor'))
        obj.size_factor = ApiClient.convertToType(data['size_factor'], 'Number');
      if (data.hasOwnProperty('solar_system_id'))
        obj.solar_system_id = ApiClient.convertToType(data['solar_system_id'], 'Number');
      if (data.hasOwnProperty('station_count'))
        obj.station_count = ApiClient.convertToType(data['station_count'], 'Number');
      if (data.hasOwnProperty('station_system_count'))
        obj.station_system_count = ApiClient.convertToType(data['station_system_count'], 'Number');
    }
    return obj;
  }

  /**
   * corporation_id integer
   * @member {Number} corporation_id
   */
  exports.prototype.corporation_id = undefined;

  /**
   * description string
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * faction_id integer
   * @member {Number} faction_id
   */
  exports.prototype.faction_id = undefined;

  /**
   * is_unique boolean
   * @member {Boolean} is_unique
   */
  exports.prototype.is_unique = undefined;

  /**
   * militia_corporation_id integer
   * @member {Number} militia_corporation_id
   */
  exports.prototype.militia_corporation_id = undefined;

  /**
   * name string
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * size_factor number
   * @member {Number} size_factor
   */
  exports.prototype.size_factor = undefined;

  /**
   * solar_system_id integer
   * @member {Number} solar_system_id
   */
  exports.prototype.solar_system_id = undefined;

  /**
   * station_count integer
   * @member {Number} station_count
   */
  exports.prototype.station_count = undefined;

  /**
   * station_system_count integer
   * @member {Number} station_system_count
   */
  exports.prototype.station_system_count = undefined;


  return exports;

}));
