/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveApi) {
      root.EveApi = {};
    }
    root.EveApi.GetUniverseBloodlines200Ok = factory(root.EveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetUniverseBloodlines200Ok model module.
   * @module model/GetUniverseBloodlines200Ok
   * @version 1.12
   */

  /**
   * Constructs a new <code>GetUniverseBloodlines200Ok</code>.
   * 200 ok object
   * @alias module:model/GetUniverseBloodlines200Ok
   * @class
   * @param bloodline_id {Number} bloodline_id integer
   * @param charisma {Number} charisma integer
   * @param corporation_id {Number} corporation_id integer
   * @param description {String} description string
   * @param intelligence {Number} intelligence integer
   * @param memory {Number} memory integer
   * @param name {String} name string
   * @param perception {Number} perception integer
   * @param race_id {Number} race_id integer
   * @param ship_type_id {Number} ship_type_id integer
   * @param willpower {Number} willpower integer
   */
  var exports = function(bloodline_id, charisma, corporation_id, description, intelligence, memory, name, perception, race_id, ship_type_id, willpower) {
    this.bloodline_id = bloodline_id;
    this.charisma = charisma;
    this.corporation_id = corporation_id;
    this.description = description;
    this.intelligence = intelligence;
    this.memory = memory;
    this.name = name;
    this.perception = perception;
    this.race_id = race_id;
    this.ship_type_id = ship_type_id;
    this.willpower = willpower;
  };

  /**
   * Constructs a <code>GetUniverseBloodlines200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUniverseBloodlines200Ok} obj Optional instance to populate.
   * @return {module:model/GetUniverseBloodlines200Ok} The populated <code>GetUniverseBloodlines200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bloodline_id'))
        obj.bloodline_id = ApiClient.convertToType(data['bloodline_id'], 'Number');
      if (data.hasOwnProperty('charisma'))
        obj.charisma = ApiClient.convertToType(data['charisma'], 'Number');
      if (data.hasOwnProperty('corporation_id'))
        obj.corporation_id = ApiClient.convertToType(data['corporation_id'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('intelligence'))
        obj.intelligence = ApiClient.convertToType(data['intelligence'], 'Number');
      if (data.hasOwnProperty('memory'))
        obj.memory = ApiClient.convertToType(data['memory'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('perception'))
        obj.perception = ApiClient.convertToType(data['perception'], 'Number');
      if (data.hasOwnProperty('race_id'))
        obj.race_id = ApiClient.convertToType(data['race_id'], 'Number');
      if (data.hasOwnProperty('ship_type_id'))
        obj.ship_type_id = ApiClient.convertToType(data['ship_type_id'], 'Number');
      if (data.hasOwnProperty('willpower'))
        obj.willpower = ApiClient.convertToType(data['willpower'], 'Number');
    }
    return obj;
  }

  /**
   * bloodline_id integer
   * @member {Number} bloodline_id
   */
  exports.prototype.bloodline_id = undefined;

  /**
   * charisma integer
   * @member {Number} charisma
   */
  exports.prototype.charisma = undefined;

  /**
   * corporation_id integer
   * @member {Number} corporation_id
   */
  exports.prototype.corporation_id = undefined;

  /**
   * description string
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * intelligence integer
   * @member {Number} intelligence
   */
  exports.prototype.intelligence = undefined;

  /**
   * memory integer
   * @member {Number} memory
   */
  exports.prototype.memory = undefined;

  /**
   * name string
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * perception integer
   * @member {Number} perception
   */
  exports.prototype.perception = undefined;

  /**
   * race_id integer
   * @member {Number} race_id
   */
  exports.prototype.race_id = undefined;

  /**
   * ship_type_id integer
   * @member {Number} ship_type_id
   */
  exports.prototype.ship_type_id = undefined;

  /**
   * willpower integer
   * @member {Number} willpower
   */
  exports.prototype.willpower = undefined;


  return exports;

}));
