/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCorporationsCorporationIdContractsContractIdBids200Ok', function() {
      beforeEach(function() {
        instance = new EveApi.GetCorporationsCorporationIdContractsContractIdBids200Ok();
      });

      it('should create an instance of GetCorporationsCorporationIdContractsContractIdBids200Ok', function() {
        // TODO: update the code to test GetCorporationsCorporationIdContractsContractIdBids200Ok
        expect(instance).to.be.a(EveApi.GetCorporationsCorporationIdContractsContractIdBids200Ok);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property bid_id (base name: "bid_id")', function() {
        // TODO: update the code to test the property bid_id
        expect(instance).to.have.property('bid_id');
        // expect(instance.bid_id).to.be(expectedValueLiteral);
      });

      it('should have the property bidder_id (base name: "bidder_id")', function() {
        // TODO: update the code to test the property bidder_id
        expect(instance).to.have.property('bidder_id');
        // expect(instance.bidder_id).to.be(expectedValueLiteral);
      });

      it('should have the property date_bid (base name: "date_bid")', function() {
        // TODO: update the code to test the property date_bid
        expect(instance).to.have.property('date_bid');
        // expect(instance.date_bid).to.be(expectedValueLiteral);
      });

    });
  });

}));
