/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCorporationsCorporationIdRolesHistory200Ok', function() {
      beforeEach(function() {
        instance = new EveApi.GetCorporationsCorporationIdRolesHistory200Ok();
      });

      it('should create an instance of GetCorporationsCorporationIdRolesHistory200Ok', function() {
        // TODO: update the code to test GetCorporationsCorporationIdRolesHistory200Ok
        expect(instance).to.be.a(EveApi.GetCorporationsCorporationIdRolesHistory200Ok);
      });

      it('should have the property changed_at (base name: "changed_at")', function() {
        // TODO: update the code to test the property changed_at
        expect(instance).to.have.property('changed_at');
        // expect(instance.changed_at).to.be(expectedValueLiteral);
      });

      it('should have the property character_id (base name: "character_id")', function() {
        // TODO: update the code to test the property character_id
        expect(instance).to.have.property('character_id');
        // expect(instance.character_id).to.be(expectedValueLiteral);
      });

      it('should have the property issuer_id (base name: "issuer_id")', function() {
        // TODO: update the code to test the property issuer_id
        expect(instance).to.have.property('issuer_id');
        // expect(instance.issuer_id).to.be(expectedValueLiteral);
      });

      it('should have the property new_roles (base name: "new_roles")', function() {
        // TODO: update the code to test the property new_roles
        expect(instance).to.have.property('new_roles');
        // expect(instance.new_roles).to.be(expectedValueLiteral);
      });

      it('should have the property old_roles (base name: "old_roles")', function() {
        // TODO: update the code to test the property old_roles
        expect(instance).to.have.property('old_roles');
        // expect(instance.old_roles).to.be(expectedValueLiteral);
      });

      it('should have the property role_type (base name: "role_type")', function() {
        // TODO: update the code to test the property role_type
        expect(instance).to.have.property('role_type');
        // expect(instance.role_type).to.be(expectedValueLiteral);
      });

    });
  });

}));
