/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCharactersCharacterIdContacts200Ok', function() {
      beforeEach(function() {
        instance = new EveApi.GetCharactersCharacterIdContacts200Ok();
      });

      it('should create an instance of GetCharactersCharacterIdContacts200Ok', function() {
        // TODO: update the code to test GetCharactersCharacterIdContacts200Ok
        expect(instance).to.be.a(EveApi.GetCharactersCharacterIdContacts200Ok);
      });

      it('should have the property contact_id (base name: "contact_id")', function() {
        // TODO: update the code to test the property contact_id
        expect(instance).to.have.property('contact_id');
        // expect(instance.contact_id).to.be(expectedValueLiteral);
      });

      it('should have the property contact_type (base name: "contact_type")', function() {
        // TODO: update the code to test the property contact_type
        expect(instance).to.have.property('contact_type');
        // expect(instance.contact_type).to.be(expectedValueLiteral);
      });

      it('should have the property is_blocked (base name: "is_blocked")', function() {
        // TODO: update the code to test the property is_blocked
        expect(instance).to.have.property('is_blocked');
        // expect(instance.is_blocked).to.be(expectedValueLiteral);
      });

      it('should have the property is_watched (base name: "is_watched")', function() {
        // TODO: update the code to test the property is_watched
        expect(instance).to.have.property('is_watched');
        // expect(instance.is_watched).to.be(expectedValueLiteral);
      });

      it('should have the property label_ids (base name: "label_ids")', function() {
        // TODO: update the code to test the property label_ids
        expect(instance).to.have.property('label_ids');
        // expect(instance.label_ids).to.be(expectedValueLiteral);
      });

      it('should have the property standing (base name: "standing")', function() {
        // TODO: update the code to test the property standing
        expect(instance).to.have.property('standing');
        // expect(instance.standing).to.be(expectedValueLiteral);
      });

    });
  });

}));
