/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCorporationsCorporationIdMedals200Ok', function() {
      beforeEach(function() {
        instance = new EveApi.GetCorporationsCorporationIdMedals200Ok();
      });

      it('should create an instance of GetCorporationsCorporationIdMedals200Ok', function() {
        // TODO: update the code to test GetCorporationsCorporationIdMedals200Ok
        expect(instance).to.be.a(EveApi.GetCorporationsCorporationIdMedals200Ok);
      });

      it('should have the property created_at (base name: "created_at")', function() {
        // TODO: update the code to test the property created_at
        expect(instance).to.have.property('created_at');
        // expect(instance.created_at).to.be(expectedValueLiteral);
      });

      it('should have the property creator_id (base name: "creator_id")', function() {
        // TODO: update the code to test the property creator_id
        expect(instance).to.have.property('creator_id');
        // expect(instance.creator_id).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property medal_id (base name: "medal_id")', function() {
        // TODO: update the code to test the property medal_id
        expect(instance).to.have.property('medal_id');
        // expect(instance.medal_id).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

    });
  });

}));
