/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCharactersCharacterIdSkillsOk', function() {
      beforeEach(function() {
        instance = new EveApi.GetCharactersCharacterIdSkillsOk();
      });

      it('should create an instance of GetCharactersCharacterIdSkillsOk', function() {
        // TODO: update the code to test GetCharactersCharacterIdSkillsOk
        expect(instance).to.be.a(EveApi.GetCharactersCharacterIdSkillsOk);
      });

      it('should have the property skills (base name: "skills")', function() {
        // TODO: update the code to test the property skills
        expect(instance).to.have.property('skills');
        // expect(instance.skills).to.be(expectedValueLiteral);
      });

      it('should have the property total_sp (base name: "total_sp")', function() {
        // TODO: update the code to test the property total_sp
        expect(instance).to.have.property('total_sp');
        // expect(instance.total_sp).to.be(expectedValueLiteral);
      });

      it('should have the property unallocated_sp (base name: "unallocated_sp")', function() {
        // TODO: update the code to test the property unallocated_sp
        expect(instance).to.have.property('unallocated_sp');
        // expect(instance.unallocated_sp).to.be(expectedValueLiteral);
      });

    });
  });

}));
