/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetCharactersCharacterIdPlanetsPlanetIdRoute', function() {
      beforeEach(function() {
        instance = new EveApi.GetCharactersCharacterIdPlanetsPlanetIdRoute();
      });

      it('should create an instance of GetCharactersCharacterIdPlanetsPlanetIdRoute', function() {
        // TODO: update the code to test GetCharactersCharacterIdPlanetsPlanetIdRoute
        expect(instance).to.be.a(EveApi.GetCharactersCharacterIdPlanetsPlanetIdRoute);
      });

      it('should have the property content_type_id (base name: "content_type_id")', function() {
        // TODO: update the code to test the property content_type_id
        expect(instance).to.have.property('content_type_id');
        // expect(instance.content_type_id).to.be(expectedValueLiteral);
      });

      it('should have the property destination_pin_id (base name: "destination_pin_id")', function() {
        // TODO: update the code to test the property destination_pin_id
        expect(instance).to.have.property('destination_pin_id');
        // expect(instance.destination_pin_id).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property route_id (base name: "route_id")', function() {
        // TODO: update the code to test the property route_id
        expect(instance).to.have.property('route_id');
        // expect(instance.route_id).to.be(expectedValueLiteral);
      });

      it('should have the property source_pin_id (base name: "source_pin_id")', function() {
        // TODO: update the code to test the property source_pin_id
        expect(instance).to.have.property('source_pin_id');
        // expect(instance.source_pin_id).to.be(expectedValueLiteral);
      });

      it('should have the property waypoints (base name: "waypoints")', function() {
        // TODO: update the code to test the property waypoints
        expect(instance).to.have.property('waypoints');
        // expect(instance.waypoints).to.be(expectedValueLiteral);
      });

    });
  });

}));
