/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetKillmailsKillmailIdKillmailHashAttacker', function() {
      beforeEach(function() {
        instance = new EveApi.GetKillmailsKillmailIdKillmailHashAttacker();
      });

      it('should create an instance of GetKillmailsKillmailIdKillmailHashAttacker', function() {
        // TODO: update the code to test GetKillmailsKillmailIdKillmailHashAttacker
        expect(instance).to.be.a(EveApi.GetKillmailsKillmailIdKillmailHashAttacker);
      });

      it('should have the property alliance_id (base name: "alliance_id")', function() {
        // TODO: update the code to test the property alliance_id
        expect(instance).to.have.property('alliance_id');
        // expect(instance.alliance_id).to.be(expectedValueLiteral);
      });

      it('should have the property character_id (base name: "character_id")', function() {
        // TODO: update the code to test the property character_id
        expect(instance).to.have.property('character_id');
        // expect(instance.character_id).to.be(expectedValueLiteral);
      });

      it('should have the property corporation_id (base name: "corporation_id")', function() {
        // TODO: update the code to test the property corporation_id
        expect(instance).to.have.property('corporation_id');
        // expect(instance.corporation_id).to.be(expectedValueLiteral);
      });

      it('should have the property damage_done (base name: "damage_done")', function() {
        // TODO: update the code to test the property damage_done
        expect(instance).to.have.property('damage_done');
        // expect(instance.damage_done).to.be(expectedValueLiteral);
      });

      it('should have the property faction_id (base name: "faction_id")', function() {
        // TODO: update the code to test the property faction_id
        expect(instance).to.have.property('faction_id');
        // expect(instance.faction_id).to.be(expectedValueLiteral);
      });

      it('should have the property final_blow (base name: "final_blow")', function() {
        // TODO: update the code to test the property final_blow
        expect(instance).to.have.property('final_blow');
        // expect(instance.final_blow).to.be(expectedValueLiteral);
      });

      it('should have the property security_status (base name: "security_status")', function() {
        // TODO: update the code to test the property security_status
        expect(instance).to.have.property('security_status');
        // expect(instance.security_status).to.be(expectedValueLiteral);
      });

      it('should have the property ship_type_id (base name: "ship_type_id")', function() {
        // TODO: update the code to test the property ship_type_id
        expect(instance).to.have.property('ship_type_id');
        // expect(instance.ship_type_id).to.be(expectedValueLiteral);
      });

      it('should have the property weapon_type_id (base name: "weapon_type_id")', function() {
        // TODO: update the code to test the property weapon_type_id
        expect(instance).to.have.property('weapon_type_id');
        // expect(instance.weapon_type_id).to.be(expectedValueLiteral);
      });

    });
  });

}));
