/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetKillmailsKillmailIdKillmailHashOk', function() {
      beforeEach(function() {
        instance = new EveApi.GetKillmailsKillmailIdKillmailHashOk();
      });

      it('should create an instance of GetKillmailsKillmailIdKillmailHashOk', function() {
        // TODO: update the code to test GetKillmailsKillmailIdKillmailHashOk
        expect(instance).to.be.a(EveApi.GetKillmailsKillmailIdKillmailHashOk);
      });

      it('should have the property attackers (base name: "attackers")', function() {
        // TODO: update the code to test the property attackers
        expect(instance).to.have.property('attackers');
        // expect(instance.attackers).to.be(expectedValueLiteral);
      });

      it('should have the property killmail_id (base name: "killmail_id")', function() {
        // TODO: update the code to test the property killmail_id
        expect(instance).to.have.property('killmail_id');
        // expect(instance.killmail_id).to.be(expectedValueLiteral);
      });

      it('should have the property killmail_time (base name: "killmail_time")', function() {
        // TODO: update the code to test the property killmail_time
        expect(instance).to.have.property('killmail_time');
        // expect(instance.killmail_time).to.be(expectedValueLiteral);
      });

      it('should have the property moon_id (base name: "moon_id")', function() {
        // TODO: update the code to test the property moon_id
        expect(instance).to.have.property('moon_id');
        // expect(instance.moon_id).to.be(expectedValueLiteral);
      });

      it('should have the property solar_system_id (base name: "solar_system_id")', function() {
        // TODO: update the code to test the property solar_system_id
        expect(instance).to.have.property('solar_system_id');
        // expect(instance.solar_system_id).to.be(expectedValueLiteral);
      });

      it('should have the property victim (base name: "victim")', function() {
        // TODO: update the code to test the property victim
        expect(instance).to.have.property('victim');
        // expect(instance.victim).to.be(expectedValueLiteral);
      });

      it('should have the property war_id (base name: "war_id")', function() {
        // TODO: update the code to test the property war_id
        expect(instance).to.have.property('war_id');
        // expect(instance.war_id).to.be(expectedValueLiteral);
      });

    });
  });

}));
