/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetUniverseGroupsGroupIdOk', function() {
      beforeEach(function() {
        instance = new EveApi.GetUniverseGroupsGroupIdOk();
      });

      it('should create an instance of GetUniverseGroupsGroupIdOk', function() {
        // TODO: update the code to test GetUniverseGroupsGroupIdOk
        expect(instance).to.be.a(EveApi.GetUniverseGroupsGroupIdOk);
      });

      it('should have the property category_id (base name: "category_id")', function() {
        // TODO: update the code to test the property category_id
        expect(instance).to.have.property('category_id');
        // expect(instance.category_id).to.be(expectedValueLiteral);
      });

      it('should have the property group_id (base name: "group_id")', function() {
        // TODO: update the code to test the property group_id
        expect(instance).to.have.property('group_id');
        // expect(instance.group_id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property published (base name: "published")', function() {
        // TODO: update the code to test the property published
        expect(instance).to.have.property('published');
        // expect(instance.published).to.be(expectedValueLiteral);
      });

      it('should have the property types (base name: "types")', function() {
        // TODO: update the code to test the property types
        expect(instance).to.have.property('types');
        // expect(instance.types).to.be(expectedValueLiteral);
      });

    });
  });

}));
