/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetUniverseTypesTypeIdDogmaEffect', function() {
      beforeEach(function() {
        instance = new EveApi.GetUniverseTypesTypeIdDogmaEffect();
      });

      it('should create an instance of GetUniverseTypesTypeIdDogmaEffect', function() {
        // TODO: update the code to test GetUniverseTypesTypeIdDogmaEffect
        expect(instance).to.be.a(EveApi.GetUniverseTypesTypeIdDogmaEffect);
      });

      it('should have the property effect_id (base name: "effect_id")', function() {
        // TODO: update the code to test the property effect_id
        expect(instance).to.have.property('effect_id');
        // expect(instance.effect_id).to.be(expectedValueLiteral);
      });

      it('should have the property is_default (base name: "is_default")', function() {
        // TODO: update the code to test the property is_default
        expect(instance).to.have.property('is_default');
        // expect(instance.is_default).to.be(expectedValueLiteral);
      });

    });
  });

}));
