/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetUniverseSystemsSystemIdOk', function() {
      beforeEach(function() {
        instance = new EveApi.GetUniverseSystemsSystemIdOk();
      });

      it('should create an instance of GetUniverseSystemsSystemIdOk', function() {
        // TODO: update the code to test GetUniverseSystemsSystemIdOk
        expect(instance).to.be.a(EveApi.GetUniverseSystemsSystemIdOk);
      });

      it('should have the property constellation_id (base name: "constellation_id")', function() {
        // TODO: update the code to test the property constellation_id
        expect(instance).to.have.property('constellation_id');
        // expect(instance.constellation_id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property planets (base name: "planets")', function() {
        // TODO: update the code to test the property planets
        expect(instance).to.have.property('planets');
        // expect(instance.planets).to.be(expectedValueLiteral);
      });

      it('should have the property position (base name: "position")', function() {
        // TODO: update the code to test the property position
        expect(instance).to.have.property('position');
        // expect(instance.position).to.be(expectedValueLiteral);
      });

      it('should have the property security_class (base name: "security_class")', function() {
        // TODO: update the code to test the property security_class
        expect(instance).to.have.property('security_class');
        // expect(instance.security_class).to.be(expectedValueLiteral);
      });

      it('should have the property security_status (base name: "security_status")', function() {
        // TODO: update the code to test the property security_status
        expect(instance).to.have.property('security_status');
        // expect(instance.security_status).to.be(expectedValueLiteral);
      });

      it('should have the property star_id (base name: "star_id")', function() {
        // TODO: update the code to test the property star_id
        expect(instance).to.have.property('star_id');
        // expect(instance.star_id).to.be(expectedValueLiteral);
      });

      it('should have the property stargates (base name: "stargates")', function() {
        // TODO: update the code to test the property stargates
        expect(instance).to.have.property('stargates');
        // expect(instance.stargates).to.be(expectedValueLiteral);
      });

      it('should have the property stations (base name: "stations")', function() {
        // TODO: update the code to test the property stations
        expect(instance).to.have.property('stations');
        // expect(instance.stations).to.be(expectedValueLiteral);
      });

      it('should have the property system_id (base name: "system_id")', function() {
        // TODO: update the code to test the property system_id
        expect(instance).to.have.property('system_id');
        // expect(instance.system_id).to.be(expectedValueLiteral);
      });

    });
  });

}));
