/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveApi.BookmarksApi();
  });

  describe('(package)', function() {
    describe('BookmarksApi', function() {
      describe('getCharactersCharacterIdBookmarks', function() {
        it('should call getCharactersCharacterIdBookmarks successfully', function(done) {
          // TODO: uncomment, update parameter values for getCharactersCharacterIdBookmarks call and complete the assertions
          /*
          var character_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.If_None_Match = "If_None_Match_example";
          opts.page = 1;
          opts.token = "token_example";

          instance.getCharactersCharacterIdBookmarks(character_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveApi.GetCharactersCharacterIdBookmarks200Ok);
              expect(data.bookmark_id).to.be.a('number');
              expect(data.bookmark_id).to.be(0);
              expect(data.coordinates).to.be.a(EveApi.GetCharactersCharacterIdBookmarksCoordinates);
                    expect(data.coordinates.x).to.be.a('number');
                expect(data.coordinates.x).to.be(0.0);
                expect(data.coordinates.y).to.be.a('number');
                expect(data.coordinates.y).to.be(0.0);
                expect(data.coordinates.z).to.be.a('number');
                expect(data.coordinates.z).to.be(0.0);
              expect(data.created).to.be.a(Date);
              expect(data.created).to.be(new Date());
              expect(data.creator_id).to.be.a('number');
              expect(data.creator_id).to.be(0);
              expect(data.folder_id).to.be.a('number');
              expect(data.folder_id).to.be(0);
              expect(data.item).to.be.a(EveApi.GetCharactersCharacterIdBookmarksItem);
                    expect(data.item.item_id).to.be.a('number');
                expect(data.item.item_id).to.be("0");
                expect(data.item.type_id).to.be.a('number');
                expect(data.item.type_id).to.be(0);
              expect(data.label).to.be.a('string');
              expect(data.label).to.be("");
              expect(data.location_id).to.be.a('number');
              expect(data.location_id).to.be(0);
              expect(data.notes).to.be.a('string');
              expect(data.notes).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCharactersCharacterIdBookmarksFolders', function() {
        it('should call getCharactersCharacterIdBookmarksFolders successfully', function(done) {
          // TODO: uncomment, update parameter values for getCharactersCharacterIdBookmarksFolders call and complete the assertions
          /*
          var character_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.If_None_Match = "If_None_Match_example";
          opts.page = 1;
          opts.token = "token_example";

          instance.getCharactersCharacterIdBookmarksFolders(character_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveApi.GetCharactersCharacterIdBookmarksFolders200Ok);
              expect(data.folder_id).to.be.a('number');
              expect(data.folder_id).to.be(0);
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCorporationsCorporationIdBookmarks', function() {
        it('should call getCorporationsCorporationIdBookmarks successfully', function(done) {
          // TODO: uncomment, update parameter values for getCorporationsCorporationIdBookmarks call and complete the assertions
          /*
          var corporation_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.If_None_Match = "If_None_Match_example";
          opts.page = 1;
          opts.token = "token_example";

          instance.getCorporationsCorporationIdBookmarks(corporation_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveApi.GetCorporationsCorporationIdBookmarks200Ok);
              expect(data.bookmark_id).to.be.a('number');
              expect(data.bookmark_id).to.be(0);
              expect(data.coordinates).to.be.a(EveApi.GetCorporationsCorporationIdBookmarksCoordinates);
                    expect(data.coordinates.x).to.be.a('number');
                expect(data.coordinates.x).to.be(0.0);
                expect(data.coordinates.y).to.be.a('number');
                expect(data.coordinates.y).to.be(0.0);
                expect(data.coordinates.z).to.be.a('number');
                expect(data.coordinates.z).to.be(0.0);
              expect(data.created).to.be.a(Date);
              expect(data.created).to.be(new Date());
              expect(data.creator_id).to.be.a('number');
              expect(data.creator_id).to.be(0);
              expect(data.folder_id).to.be.a('number');
              expect(data.folder_id).to.be(0);
              expect(data.item).to.be.a(EveApi.GetCorporationsCorporationIdBookmarksItem);
                    expect(data.item.item_id).to.be.a('number');
                expect(data.item.item_id).to.be("0");
                expect(data.item.type_id).to.be.a('number');
                expect(data.item.type_id).to.be(0);
              expect(data.label).to.be.a('string');
              expect(data.label).to.be("");
              expect(data.location_id).to.be.a('number');
              expect(data.location_id).to.be(0);
              expect(data.notes).to.be.a('string');
              expect(data.notes).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCorporationsCorporationIdBookmarksFolders', function() {
        it('should call getCorporationsCorporationIdBookmarksFolders successfully', function(done) {
          // TODO: uncomment, update parameter values for getCorporationsCorporationIdBookmarksFolders call and complete the assertions
          /*
          var corporation_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.If_None_Match = "If_None_Match_example";
          opts.page = 1;
          opts.token = "token_example";

          instance.getCorporationsCorporationIdBookmarksFolders(corporation_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveApi.GetCorporationsCorporationIdBookmarksFolders200Ok);
              expect(data.creator_id).to.be.a('number');
              expect(data.creator_id).to.be(0);
              expect(data.folder_id).to.be.a('number');
              expect(data.folder_id).to.be(0);
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
