/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EveApi);
  }
}(this, function(expect, EveApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EveApi.CalendarApi();
  });

  describe('(package)', function() {
    describe('CalendarApi', function() {
      describe('getCharactersCharacterIdCalendar', function() {
        it('should call getCharactersCharacterIdCalendar successfully', function(done) {
          // TODO: uncomment, update parameter values for getCharactersCharacterIdCalendar call and complete the assertions
          /*
          var character_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.from_event = 56;
          opts.If_None_Match = "If_None_Match_example";
          opts.token = "token_example";

          instance.getCharactersCharacterIdCalendar(character_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveApi.GetCharactersCharacterIdCalendar200Ok);
              expect(data.event_date).to.be.a(Date);
              expect(data.event_date).to.be(new Date());
              expect(data.event_id).to.be.a('number');
              expect(data.event_id).to.be(0);
              expect(data.event_response).to.be.a('string');
              expect(data.event_response).to.be("declined");
              expect(data.importance).to.be.a('number');
              expect(data.importance).to.be(0);
              expect(data.title).to.be.a('string');
              expect(data.title).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCharactersCharacterIdCalendarEventId', function() {
        it('should call getCharactersCharacterIdCalendarEventId successfully', function(done) {
          // TODO: uncomment, update parameter values for getCharactersCharacterIdCalendarEventId call and complete the assertions
          /*
          var character_id = 56;
          var event_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.If_None_Match = "If_None_Match_example";
          opts.token = "token_example";

          instance.getCharactersCharacterIdCalendarEventId(character_id, event_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EveApi.GetCharactersCharacterIdCalendarEventIdOk);
            expect(data._date).to.be.a(Date);
            expect(data._date).to.be(new Date());
            expect(data.duration).to.be.a('number');
            expect(data.duration).to.be(0);
            expect(data.event_id).to.be.a('number');
            expect(data.event_id).to.be(0);
            expect(data.importance).to.be.a('number');
            expect(data.importance).to.be(0);
            expect(data.owner_id).to.be.a('number');
            expect(data.owner_id).to.be(0);
            expect(data.owner_name).to.be.a('string');
            expect(data.owner_name).to.be("");
            expect(data.owner_type).to.be.a('string');
            expect(data.owner_type).to.be("eve_server");
            expect(data.response).to.be.a('string');
            expect(data.response).to.be("");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("");
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCharactersCharacterIdCalendarEventIdAttendees', function() {
        it('should call getCharactersCharacterIdCalendarEventIdAttendees successfully', function(done) {
          // TODO: uncomment, update parameter values for getCharactersCharacterIdCalendarEventIdAttendees call and complete the assertions
          /*
          var character_id = 56;
          var event_id = 56;
          var opts = {};
          opts.datasource = "tranquility";
          opts.If_None_Match = "If_None_Match_example";
          opts.token = "token_example";

          instance.getCharactersCharacterIdCalendarEventIdAttendees(character_id, event_id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EveApi.GetCharactersCharacterIdCalendarEventIdAttendees200Ok);
              expect(data.character_id).to.be.a('number');
              expect(data.character_id).to.be(0);
              expect(data.event_response).to.be.a('string');
              expect(data.event_response).to.be("declined");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putCharactersCharacterIdCalendarEventId', function() {
        it('should call putCharactersCharacterIdCalendarEventId successfully', function(done) {
          // TODO: uncomment, update parameter values for putCharactersCharacterIdCalendarEventId call
          /*
          var character_id = 56;
          var event_id = 56;
          var response = new EveApi.PutCharactersCharacterIdCalendarEventIdResponse();
          response.response = "accepted";
          var opts = {};
          opts.datasource = "tranquility";
          opts.token = "token_example";

          instance.putCharactersCharacterIdCalendarEventId(character_id, event_id, response, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
